### ISSUE TITLE
Not Found ;(

### ISSUE THREAD

**Issue by freazesss** [HakaCode/hakacode.github.io#1]
![image](https://user-images.githubusercontent.com/60306241/87867858-7fbb0980-c967-11ea-865a-2fa518ce95c8.png)

Eu acho que você esqueceu de criar a branch **GH-PAGES**.

**Comment by HakaCode** [comment]
@freazesss esse trem de github pages ta com problema

![](https://image.prntscr.com/image/JIVSqfUfQKWgcrfZXDqTiw.png)

**Comment by freazesss** [comment]
Cria uma branch chamada **gh-pages** que funfa de boa.

**Comment by HakaCode** [comment]
Obrigado pelo aviso @freazesss
